# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    #(modulesPath + "/installer/scan/not-detected.nix")
  ];

  #boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ata_piix" "ahci" "firewire_ohci" "usb_storage" "sd_mod" ];
  #boot.initrd.kernelModules = [ ];
  #boot.kernelModules = [ "kvm-intel" ];
  #boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9b33439a-dc9a-4426-85ef-3e672cdc72ac";
      fsType = "ext4";
      #fsType = lib.mkForce "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/7dd05095-546c-44dc-b9be-bfecceaaa6ec"; }
    ];

  #nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  #networking.enableIntel3945ABGFirmware = true;
  #hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
