# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-d5c48378-dac8-42d2-9fe7-1278fb31e8ee";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-d5c48378-dac8-42d2-9fe7-1278fb31e8ee".device = "/dev/disk/by-uuid/d5c48378-dac8-42d2-9fe7-1278fb31e8ee";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/15D9-313A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-f3fa1ee5-9218-41a2-a0d5-78c0cb17f758"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
