# profiles/nixos/hosts/nyxora/services/waktusolat-aggregator.nix

#
# NOTE:
#   nyxora runs only the Aggregator service, omitting the Client service
#   entirely to prevent duplicate fetch loops.
#

{ config, pkgs, inputs, ... }:

let
  # Convenience reference to packages built by the waktusolat flake
  waktusolatPkgs = inputs.waktusolat.packages.${pkgs.system};
in
{
  # 1. Import the Aggregator module (origin node for your LAN)
  imports = [
    inputs.waktusolat.nixosModules.aggregator
  ];

  # 2. Enable & configure the Aggregator daemon and HTTP file server
  services.waktusolatAggregator = {
    enable = true;
    zones = [ "SGR01" ];
    port = 8089;
    dataDir = "/var/lib/waktusolat";
    logLevel = "INFO";
  };

  # 3. Install xmobar renderers and CLI tool on nyxora
  environment.systemPackages = [
    waktusolatPkgs.render-xmobar
    waktusolatPkgs.render-waybar
    waktusolatPkgs.cli
  ];

  # 4. Export session variables so xmobar reads from the Aggregator's data directory
  #
  # (Note: Requires logging out and back in, or restarting xmonad/xmobar from a
  # fresh login shell for the session environment to be inherited).
  #
  environment.sessionVariables = {

    #
    # Explicitly exporting WAKTUSOLAT_DATA_DIR = "/var/lib/waktusolat" ensures
    # xmobar reads the live file generated by services.waktusolatAggregator
    # rather than defaulting to /var/cache/waktusolat
    #
    WAKTUSOLAT_DATA_DIR = "/var/lib/waktusolat";

    WAKTUSOLAT_ZONE = "SGR01";

  };
}
