# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  #boot.kernelPackages = lib.mkDefault pkgs.linuxPackages_latest;
  #boot.kernelPackages = config.boot.zfs.package.latestCompatibleLinuxPackages;  # Do not need it here; as I already define in zfs.nix

  boot.kernelModules =                 [ "kvm-intel" ];
  boot.extraModulePackages =           [ ];
  boot.supportedFilesystems =          [
    "btrfs" "ext4" "xfs" "vfat" "ntfs"
    # "bcachefs"
    "dm-crypt" "dm-snapshot" "dm-raid"
    "zfs"
  ];

  boot.initrd = {
    availableKernelModules = [
      "ehci_pci" "ahci" "xhci_pci" "ata_piix" "usbhid" "usb_storage" "sd_mod" "mpt3sas"
      "uhci_hcd" "firewire_ohci" "sr_mod" "sdhci_pci"
      "ums_realtek"
      "mpt3sas"
    ];
    kernelModules = [
      "btrfs" "ext4" "xfs" "vfat" "dm-crypt" "dm-snapshot" "dm-raid" "zfs"
      #"ntfs"
      "kvm-intel"
    ];            #"zfs" "bcachefs"
    supportedFilesystems = [
      "btrfs" "ext4" "xfs" "vfat" "dm-crypt" "dm-snapshot" "dm-raid" "zfs"
      #"ntfs"
    ];            #"zfs" "bcachefs"

    #--------------------------------------------------------------------------
    # NOTES:
    #--------------------------------------------------------------------------
    # /dev/sda2 --> LUKS --> LVM --> btrfs
    # /dev/sdb2 --> LUKS --> LVM --> btrfs
    # lsblk
    # blkid /dev/sdb2
    # blkid /dev/sda2
    #
    # ps -eaf | grep [u]disk
    # udiskctl status
    # #lsof -p $(pidof udiskd) | tail
    # ls -FilahR /dev/disk | grep sdg
    #--------------------------------------------------------------------------

    #luks.devices."crypt1" = {
    #  device = "/dev/disk/by-uuid/552eb401-53a0-43d2-9782-26d28796b6a0"; # /dev/sdb2; 2nd partition on 254GB SSD?
    #  preLVM = true;
    #};

    # This HDD is failing
    #luks.devices."crypt2" = {
    #  device = "/dev/disk/by-uuid/b382a40d-a780-4eb3-835e-f064039af496"; #/dev/sda2; 2nd partition on 500GB HDD?
    #  preLVM = true;
    #};

    #luks.devices."crypt-d47246ca-80af-4cef-b098-29785152ce44" = { device = "/dev/disk/by-uuid/d47246ca-80af-4cef-b098-29785152ce44"; };

    #------------------
    # For OS (nixos)
    #------------------

    # AGI SSD 256GB
    #luks.devices."luks-bcd7371c-c49a-4b74-a041-9cf9728cf395" = {
    #  device = "/dev/disk/by-uuid/bcd7371c-c49a-4b74-a041-9cf9728cf395";
    #  #preLVM = true;
    #};   # xfs (nixos)
    # swap (AGI SSD)
    #luks.devices."luks-781bbff1-508d-4287-a748-63d45d74b5e5" = {
    #  device = "/dev/disk/by-uuid/781bbff1-508d-4287-a748-63d45d74b5e5";
    #  #preLVM = true;
    #};

    #------------------
    # NixOS (disk from sakinah)
    # update on 2024-06-12: HDD ni ada problem IO error
    #------------------
    # For '/' partition
    #luks.devices."luks-34a274e3-4353-430f-8ded-9354cd8acab5".device = "/dev/disk/by-uuid/34a274e3-4353-430f-8ded-9354cd8acab5";
    # For swap partition
    #luks.devices."luks-745aa30d-5f90-4d57-8193-c380ed2ece24".device = "/dev/disk/by-uuid/745aa30d-5f90-4d57-8193-c380ed2ece24";

    #------------------
    # For data storage (zfs pool: najibzfspool1)
    #------------------

    # najibzfspool1, mirror-0
    #luks.devices."luks-8a53d158-ba69-47a1-9329-2d07372949d6" = {
    #  device = "/dev/disk/by-uuid/8a53d158-ba69-47a1-9329-2d07372949d6";
    #  #preLVM = true;
    #};

    # tak detect
    #luks.devices."luks-3f373d53-ded5-481a-a6f2-c547a3593243" = {
    #  device = "/dev/disk/by-uuid/3f373d53-ded5-481a-a6f2-c547a3593243";
    #  #preLVM = true;
    #};

    #luks.devices."luks-0de82803-40d1-4fdf-8841-6e4f79e0394c" = {
    #  device = "/dev/disk/by-uuid/0de82803-40d1-4fdf-8841-6e4f79e0394c";
    #  preLVM = true;
    #};

    # najibzfspool1, mirror-1
    #luks.devices."luks-b25e6a23-1c8b-4037-8f00-5e8c51fa2c27" = {
    #  device = "/dev/disk/by-uuid/b25e6a23-1c8b-4037-8f00-5e8c51fa2c27";
    #  #preLVM = true;
    #};

    # najibzfspool1, mirror-2
    #luks.devices."luks-ec2dca2b-84e7-4d33-b6fd-7bdad06ec445" = {
    #  device = "/dev/disk/by-uuid/ec2dca2b-84e7-4d33-b6fd-7bdad06ec445";
    #  #preLVM = true;
    #};                  # 1TB, bought used-hdd from Shopee on 2023-04.
    #luks.devices."luks-acfbbc38-c2c4-453f-b995-f02f8cf17bac" = {
    #  device = "/dev/disk/by-uuid/acfbbc38-c2c4-453f-b995-f02f8cf17bac";
    #  #preLVM = true;
    #};                  # 1TB, bought used-hdd from Shopee on 2023-04.
    #luks.devices."luks-135621a1-9dfa-467a-a3fd-ab66b21e38d6" = {
    #  device = "/dev/disk/by-uuid/135621a1-9dfa-467a-a3fd-ab66b21e38d6";
    #  #preLVM = true;
    #};

    # hot spare ?
    #...

  };

  #------------------------------------
  #------------------------------------
  fileSystems."/" = {
    #device = "/dev/mapper/crypt-d47246ca-80af-4cef-b098-29785152ce44";
    #fsType = "btrfs";
    #options = [
    #  "subvol=nixos"
    #  "compress=zstd" "noatime" "autodefrag"
    #];

    # SSD AGI customdesktop
    #device = "/dev/disk/by-uuid/a64b6850-5e88-4cc3-b106-28a724c4b2cc";
    #fsType = "xfs";

    # HDD from sakinah
    # Update on 2024-06-12, HDD ni ada masalah IO error
    #device = "/dev/disk/by-uuid/606e7695-318c-4105-b4fe-ca0db0343b84";
    #fsType = "ext4";

    # 1TB HDD from hidayah (HP ProDesk Naqib)
    device = "/dev/disk/by-uuid/f7dbf09e-c9b0-4e27-9ded-3a31b43760b0";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    # customdesktop
    #device = "/dev/disk/by-uuid/bdccf3bb-061c-40d5-82c3-d04ccf603485";
    #fsType = "ext4";

    # hdd from sakinah
    #device = "/dev/disk/by-uuid/FD6B-4835";
    #fsType = "vfat";

    # HDD from hidayah
    device = "/dev/disk/by-uuid/E127-10B1";
    fsType = "vfat";
  };

  #fileSystems."/home" = {
  #  device = "najibzfspool1/home";
  #  fsType = "zfs";
  #};
  #fileSystems."/mnt/data" = {
  #  device = "najibzfspool1/home";
  #  fsType = "zfs";
  #};

  #fileSystems."/root" = {
    #device = "/dev/mapper/crypt-d47246ca-80af-4cef-b098-29785152ce44";
    #fsType = "btrfs";
    #options = [
    #  "subvol=root"
    #  "compress=zstd" "noatime" "autodefrag"
    #];

  #  device = "najibzfspool1/root";
  #  fsType = "zfs";
  #};
  #------------------------------------

  #fileSystems."/nix" =
  #  {
  #    device = "/dev/mapper/crypt-d47246ca-80af-4cef-b098-29785152ce44";
  #    fsType = "btrfs";
  #    options = [
  #      "subvol=nix"
  #      "compress=zstd" "noatime" "autodefrag"
  #    ];
  #  };

  #fileSystems."/home/data" =
  #  { device = "/dev/disk/by-uuid/873d4891-8d71-4e7a-975d-84d8342559c2";
  #    fsType = "btrfs";
  #    options = [
  #      "subvol=data"
  #      "compress=zstd" "noatime" "autodefrag"
  #    ];
  #  };

  #fileSystems."/home" = {
  #    device = "/dev/mapper/crypt-d47246ca-80af-4cef-b098-29785152ce44";
  #    fsType = "btrfs";
  #    options = [
  #      "subvol=home"
  #      "compress=zstd" "noatime" "autodefrag"
  #    ];
  #};

  #fileSystems."/home/najib" =
  #  {
  #    #device = "/dev/disk/by-uuid/873d4891-8d71-4e7a-975d-84d8342559c2";
  #    device = "/dev/mapper/crypt-d47246ca-80af-4cef-b098-29785152ce44";
  #    fsType = "btrfs";
  #    options = [
  #      "subvol=najib"
  #      "compress=zstd" "noatime" "autodefrag"
  #    ];
  #  };

  #fileSystems."/home/julia" =
  #  { device = "/dev/disk/by-uuid/873d4891-8d71-4e7a-975d-84d8342559c2";
  #    fsType = "btrfs";
  #    options = [
  #      "subvol=julia"
  #      "compress=zstd" "noatime" "autodefrag"
  #    ];
  #  };

  #fileSystems."/home/naqib" =
  #  { device = "/dev/disk/by-uuid/873d4891-8d71-4e7a-975d-84d8342559c2";
  #    fsType = "btrfs";
  #    options = [
  #      "subvol=naqib"
  #      "compress=zstd" "noatime" "autodefrag"
  #    ];
  #  };

  #fileSystems."/home/nurnasuha" =
  #  { device = "/dev/disk/by-uuid/873d4891-8d71-4e7a-975d-84d8342559c2";
  #    fsType = "btrfs";
  #    options = [
  #      "subvol=nurnasuha"
  #      "compress=zstd" "noatime" "autodefrag"
  #    ];
  #  };

  #fileSystems."/home/naim" =
  #  {
  #    device = "/dev/disk/by-uuid/873d4891-8d71-4e7a-975d-84d8342559c2";
  #    fsType = "btrfs";
  #    options = [
  #      "subvol=naim"
  #      "compress=zstd" "noatime" "autodefrag"
  #    ];
  #  };

  # Move to/etc/nixos/btrbk-pull.nix.
  #fileSystems."/mnt/btrbk_pool" = #"/mnt2" =
  #  {
  #    #device = "/dev/disk/by-uuid/37501eaa-13b2-44ac-a8d8-4e62b7803cd5";
  #    device = "/dev/mapper/lvmvg1-lvmlvroot1";
  #    fsType = "btrfs";
  #    options = ["subvolid=5"
  #      "compress=zstd" "noatime" "autodefrag"
  #    ];
  #  };

  #fileSystems."/boot" = {
  #  #device = "/dev/disk/by-uuid/7e9237ab-5825-42b5-b105-61aad181545e";
  #  #device = "/dev/disk/by-uuid/52794df2-a415-4dba-8203-949381c5c00a"; # boot partition on 254GB SSD
  #  device = "/dev/disk/by-uuid/52794df2-a415-4dba-8203-949381c5c00a";
  #    fsType = "ext4";
  #};

  # This HDD is failing
  #fileSystems."/boot2" = {
  #    device = "/dev/disk/by-uuid/7e9237ab-5825-42b5-b105-61aad181545e";
  #    fsType = "ext4";
  #};

  #fileSystems."/swap" = {
  #  device = "/dev/mapper/crypt-d47246ca-80af-4cef-b098-29785152ce44";
  #  fsType = "btrfs";
  #  options = [
  #    "subvol=swap"
  #    "noatime"
  #  ];
  #};

  swapDevices =  [
    #{ device = "/dev/disk/by-uuid/54a11355-d334-46c5-8cbb-43369d08fd8a"; } # swap on 500GB HD. This HDD is failing
    #{ device = "/dev/disk/by-uuid/600ebd52-edd2-4c42-b3b1-b8d8a6cb5acf"; } # swap partition on 254GB SSD

    #{ device = "/dev/disk/by-uuid/79d45678-d31b-4b39-851b-f00559ea8cc6"; } # AGI SSD customdesktop
    #{ device = "/dev/mapper/luks-781bbff1-508d-4287-a748-63d45d74b5e5"; }

    #{ device = "/dev/disk/by-uuid/615add4b-eb31-4d5f-82e5-7f17387307c5"; } # HDD from sakinah

    { device = "/dev/disk/by-uuid/1f6b478f-a5ad-4e66-aef8-951f340b7b78"; } # HDD from hidayah
    #{ device = "/dev/disk/by-uuid/c367f2dc-b870-4675-a75a-8f0fd7e286b0"; } # HDD from hidayah

    #{
    #  device = "/swap/swapfile";
    #  #priority = 0;
    #  size = (1024 * 12) * 2;
    #}
  ];

  networking.useDHCP = lib.mkDefault true;
  #networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform.system = "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
