# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.kernelModules = [
    "kvm-intel"
    #"wl" "88x2bu" "8812au"
  ];
  boot.extraModulePackages = [
    #config.boot.kernelPackages.broadcom_sta
    #config.boot.kernelPackages.rtl88x2bu
  ];
  boot.supportedFilesystems = [
    "btrfs" "ext4" "xfs" "vfat" "zfs" "ntfs"
    #"bcachefs"
  ];

  boot.initrd = {
    availableKernelModules = [
      "xhci_pci" "ehci_pci" "ahci" "usbhid" "ums_realtek" "usb_storage" "sd_mod" "sr_mod"
      "ata_piix" "mpt3sas"
      #"sdhci_pic"
    ];
    kernelModules = [
      "kvm-intel"
      "btrfs" "ext4" "xfs" "vfat" "dm-crypt" "dm-snapshot" "dm-raid" "zfs"
      #"zfs" "bcachefs"
    ];
    supportedFilesystems = [
      "btrfs" "ext4" "xfs" "vfat" "dm-crypt" "dm-snapshot" "dm-raid" "zfs"
      #"zfs" "bcachefs"
    ];

    #--------------------------------------------------------------------------
    # NOTES:
    #--------------------------------------------------------------------------
    # /dev/sda2 --> LUKS --> LVM --> btrfs
    # /dev/sdb2 --> LUKS --> LVM --> btrfs
    # lsblk
    # blkid /dev/sdb2
    # blkid /dev/sda2
    #
    # ps -eaf | grep [u]disk
    # udiskctl status
    # #lsof -p $(pidof udiskd) | tail
    # ls -FilahR /dev/disk | grep sdg
    #--------------------------------------------------------------------------

    #--------------------------------------------------------------------------
    # Open LUKS encrypted device
    #--------------------------------------------------------------------------
    # '/'
    luks.devices."luks-c7650c0c-d344-4e0a-8590-fa3dd49088f4" = {
      device = "/dev/disk/by-uuid/c7650c0c-d344-4e0a-8590-fa3dd49088f4";
      #preLVM = true;
    };

    # swap
    luks.devices."luks-9f205856-b2d4-459b-ad0a-2bf8e230a7ca" = {
      device = "/dev/disk/by-uuid/9f205856-b2d4-459b-ad0a-2bf8e230a7ca";
    };
    #--------------------------------------------------------------------------

  }; # Endf boot.initrd

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/e7cd3be8-b78f-4fe4-98ad-b204ae86cbf6";
    fsType = "btrfs";
    options = [
      "subvol=@"
      #"compress=zstd" "noatime" "autodefrag"
    ];
  };

  fileSystems."/boot" = {
    #device = "/dev/disk/by-uuid/16B8-42E5";
    device = "/dev/disk/by-uuid/110C-CEC0";
    fsType = "vfat";
    #options = [
    #  "subvol=swap"
    #  "noatime"
    #];
  };

  swapDevices =  [
    { device = "/dev/disk/by-uuid/0a2a334b-66f7-4fa3-aea1-d111a480e83f"; }

    #{
    #  device = "/swap/swapfile";
    #  #priority = 0;
    #  size = (1024 * 12) * 2;
    #}
  ];

  networking.useDHCP = lib.mkDefault true;
  #networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform.system = "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
