# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "firewire_ohci" "sd_mod" "sdhci_pci" ];
  #boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  #boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0ec10b45-150b-4092-b13d-fd64f50b8109";
      fsType = "btrfs";
      options = [ "subvol=root" "noatime" "nodiratime" "compress=zstd" "autodefrag" ];
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/c84ed0e7-e049-4acd-af79-de0d4d782631";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5310efa8-7d70-4f87-a720-cb5436205c2d";
      fsType = "ext4";
      options = [ "noatime" "nodiratime" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/c4598e27-5a44-4dd6-b1cc-25bb7591d09a"; }
    ];

  #nix.maxJobs = lib.mkDefault 1; #4;
}
