# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "firewire_ohci" "usb_storage" "sd_mod" "sdhci_pci" ];
  #boot.initrd.kernelModules = [ "dm-snapshot" ]; # Look below
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

#--------------------------------------------------------------------

 boot.initrd = {

      # /dev/sda.. --> crypt --> btrfs
      luks.devices."crypt1" = {
          device = "/dev/disk/by-uuid/c5d49ad4-d678-4b73-906e-9142f70edc6a"; 
          preLVM = true;
          #keyFile =
          #allowDiscards =
      };

      # /dev/sdb.. --> crypt --> btrfs
      luks.devices."crypt2" = {
          device = "/dev/disk/by-uuid/17b47f8c-916a-42b7-bc30-6b8cbe887a83";
          preLVM = true;
      };

      #secrets =
  };

 # for bringing in filesystem modules.
  boot.initrd.supportedFilesystems = [
      "btrfs"
      "ext4"
      #"zfs"
      "xfs"
      #"bcachefs"
      "vfat"
      "dm-crypt"
      "dm-snapshot"
      "dm-raid"
  ];

  #
  boot.initrd.kernelModules = [
      "btrfs"
      "ext4"
      #"zfs"
      "xfs"
      #"bcachefs"
      "vfat"
      "dm-crypt"
      "dm-snapshot"
      "dm-raid"
  ];

  boot.supportedFilesystems = [
      "ext4"
      "btrfs"
      "xfs"
      #"bcachefs"
      #"zfs"
      "vfat"
  ];


#--------------------------------------------------------------------

  fileSystems."/" =
    { 
      device = "/dev/disk/by-uuid/15762a77-c5ef-4eb0-9a5e-946646691a37";
      fsType = "btrfs";
      options = [
        "subvol=nixos" "compress=zstd" "autodefrag"
        #"noatime"
      ];
    };

  fileSystems."/root" =
    { 
      device = "/dev/disk/by-uuid/15762a77-c5ef-4eb0-9a5e-946646691a37";
      fsType = "btrfs";
      options = [
        "subvol=rootuserhome" "compress=zstd" "autodefrag"
        #"noatime"
      ];
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/15762a77-c5ef-4eb0-9a5e-946646691a37";
      fsType = "btrfs";
      options = [
        "subvol=home" "compress=zstd" "autodefrag" 
	#"noatime"
      ];
    };

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/15762a77-c5ef-4eb0-9a5e-946646691a37";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd" "autodefrag" "noatime" ];
    };



#-------------------------------------------------------------------------------

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5ec78318-f2c0-4d21-bef9-0bdfea8b6cd2";
      fsType = "ext4";
    };

  fileSystems."/boot2" =
    { device = "/dev/disk/by-uuid/9c121e78-d95a-4462-a9c2-1f8691dcffd3";
      fsType = "ext4";
    };

#-------------------------------------------------------------------------------

  swapDevices =
    [
      { device = "/dev/disk/by-uuid/b44ed253-daff-4c75-912a-2b4801611a15"; }    # /dev/sda --> /dev/sda2 --> /dev/mapper/crypt1 --> /dev/mapper/vg1-lvswap1
      { device = "/dev/disk/by-uuid/a2b9c885-9d46-41c0-aa42-8c310f12d3ef"; }    # /dev/sdb --> /dev/sdb2 --> /dev/mapper/crypt2 --> /dev/mapper/vg2-lvswap2
    ];

#-------------------------------------------------------------------------------

  nixpkgs.hostPlatform.system = "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
