# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "firewire_ohci" "usb_storage" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ "dm-snapshot" "dm-crypt" "dm-raid" "btrfs" "ext4" "xfs" "vfat" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  #----------------------------------------------------------------------------
  fileSystems."/" =
    { device = "/dev/mapper/luks-9f449c0e-0cb8-4456-b2e6-0e2e46a09d4b";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" "noatime" "autodefrag" ];
    };

  boot.initrd.luks.devices."luks-9f449c0e-0cb8-4456-b2e6-0e2e46a09d4b" = {
    device = "/dev/disk/by-uuid/9f449c0e-0cb8-4456-b2e6-0e2e46a09d4b";
    #preLVM = true;
  };
  #----------------------------------------------------------------------------

  fileSystems."/home" =
    { device = "/dev/mapper/luks-9f449c0e-0cb8-4456-b2e6-0e2e46a09d4b";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" "noatime" "autodefrag" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/b6680943-150d-4337-b114-3a788d21be94";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/2cc6a41e-5b8e-42ec-a406-93e13e94f5ed"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s25.useDHCP = lib.mkDefault true;
  # networking.interfaces.wls1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform.system = "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
