# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "firewire_ohci" "usb_storage" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8636a7e7-ff81-45c7-8d8f-83814b0d50b2";
      fsType = "ext4";
      options = [ "noatime" "nodiratime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/c10d6b59-436c-4e02-a30e-bba6828b3308";
      fsType = "ext4";
      options = [ "noatime" "nodiratime" ];
    };

  fileSystems."/root" =
    { device = "/dev/disk/by-uuid/5aeecfdc-bd03-444c-95e5-fbe673911cdb";
      fsType = "ext4";
      options = [ "noatime" "nodiratime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/0e2a01d6-416d-4ce5-904e-f824324b16f1";
      fsType = "ext4";
      options = [ "noatime" "nodiratime" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/d9dcad99-7ec7-4922-b381-845310223041"; }
    ];

  nixpkgs.hostPlatform.system = "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

}
