# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "firewire_ohci" "sd_mod" "sdhci_pci" ];
  #boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  
#--------------------------------------------------------------------

 boot.initrd = {

      # /dev/sda2 --> crypt --> LVM --> btrfs
      luks.devices."crypt1" = {
          device = "/dev/disk/by-uuid/c5d49ad4-d678-4b73-906e-9142f70edc6a"; #"/dev/disk/by-uuid/9273e024-1e66-4bdf-affb-1b26c647f78f";
          preLVM = true;
          #keyFile =
          #allowDiscards =
      };

      # /dev/sdb2 --> crypt --> LVM --> btrfs
      #luks.devices."crypt2" = {
      #    device = "/dev/disk/by-uuid/f6bd180c-6557-476b-890e-fd958046f466"; # "/dev/disk/by-uuid/GBeXRg-fwsa-X3bX-Buhe-8FiG-qqm4-0>
      #    preLVM = true;
      #};
      luks.devices."crypt2" = {
          device = "/dev/disk/by-uuid/17b47f8c-916a-42b7-bc30-6b8cbe887a83";
          preLVM = true;
      };

      #secrets =
  };

 # for bringing in filesystem modules.
  boot.initrd.supportedFilesystems = [
      "btrfs"
      "ext4"
      #"zfs"
      "xfs"
      #"bcachefs"
      "vfat"
      "dm-crypt"
      "dm-snapshot"
      "dm-raid"
  ];

  #
  boot.initrd.kernelModules = [
      "btrfs"
      "ext4"
      #"zfs"
      "xfs"
      #"bcachefs"
      "vfat"
      "dm-crypt"
      "dm-snapshot"
      "dm-raid"
  ];

  boot.supportedFilesystems = [
      "ext4"
      "btrfs"
      "xfs"
      #"bcachefs"
      #"zfs"
      "vfat"
  ];


#--------------------------------------------------------------------

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c959cd6c-4f5a-4bd4-ba22-3d1351372228";
      fsType = "btrfs";
      options = [ "subvol=nixos" "compress=zstd" "autodefrag" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/c959cd6c-4f5a-4bd4-ba22-3d1351372228";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" "autodefrag" "noatime" ];
    };

  fileSystems."/home/najib" =
    { device = "/dev/disk/by-uuid/c959cd6c-4f5a-4bd4-ba22-3d1351372228";
      fsType = "btrfs";
      options = [ "subvol=najib" "compress=zstd" "autodefrag" "noatime" ];
    };

  fileSystems."/home/DATA" =
    { device = "/dev/disk/by-uuid/c959cd6c-4f5a-4bd4-ba22-3d1351372228";
      fsType = "btrfs";
      options = [ "subvol=DATA" "compress=zstd" "autodefrag" "noatime" ];
    };

  fileSystems."/root" =
    { device = "/dev/disk/by-uuid/c959cd6c-4f5a-4bd4-ba22-3d1351372228";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd" "autodefrag" "noatime" ];
    };

  fileSystems."/home/julia" =
    { device = "/dev/disk/by-uuid/c959cd6c-4f5a-4bd4-ba22-3d1351372228";
      fsType = "btrfs";
      options = [ "subvol=juliani" "compress=zstd" "autodefrag" "noatime" ];
    };

#-------------------------------------------------------------------------------

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5ec78318-f2c0-4d21-bef9-0bdfea8b6cd2";
      fsType = "ext4";
    };

  swapDevices =
    [
      #{ device = "/dev/disk/by-uuid/271b7f30-7bf5-48d0-86e5-efe7c12512c1"; }
      { device = "/dev/disk/by-uuid/b44ed253-daff-4c75-912a-2b4801611a15"; }
    ];

  nixpkgs.hostPlatform.system = "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
