# vim: set ts=4 sw=4 nowrap number:

# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
    config,
    lib,

    pkgs,
    #sources ? import ./nix/sources.nix,
    #pkgs ? import sources.nixpkgs {},

    ...
}:

{
    #imports = [
        #<nixpkgs/nixos/modules/installer/scan/not-detected.nix>
        #(modulesPath + "/installer/scan/not-detected.nix")
        #];

      boot.initrd = {
        availableKernelModules = [
            "ehci_pci"
            "ahci"
            "firewire_ohci"
            "usbhid"
            "usb_storage"
            "sd_mod"
            "sdhci_pci"
        ];
        kernelModules = [
            "btrfs"
            "ext4"
            "xfs"
            #"bcachefs"
            "vfat"
            "dm-crypt"
            "dm-snapshot"
            "dm-raid"
        ];

        #luks.devices."crypt1" = {};

        luks.devices."crypt2" = {
            device = "/dev/disk/by-uuid/21239244-6e18-4d53-aa95-585e81f0a221";
            preLVM = true;
        };

        supportedFilesystems = [
            "ext4" "btrfs" "xfs"
            #"bcachefs"
            "vfat"
            "dm-crypt"
            "dm-snapshot"
            "dm-raid"
        ];
    };

    boot.kernelModules = [ "kvm-intel" ];
    boot.extraModulePackages = [ ];

  #----------------------------------------------------------------------------
  # OLD: sda (120GB SSD)
  #----------------------------------------------------------------------------
  #
  #fileSystems."/" =
  #  { device = "/dev/disk/by-uuid/c07236bc-55f5-4696-af35-6aa2bc996c41";
  #    fsType = "xfs";
  #    options = [ "noatime" "nodiratime" ];
  #  };
  #
  #fileSystems."/boot" =
  #  { device = "/dev/disk/by-uuid/da50ae46-98cb-4592-b192-3cb9d442fdba";
  #    fsType = "ext4";
  #    options = [ "noatime" "nodiratime" ];
  #  };
  #
  #swapDevices =
  #  [ { device = "/dev/disk/by-uuid/271b7f30-7bf5-48d0-86e5-efe7c12512c1"; }
  #  ];

  #----------------------------------------------------------------------------
  # NEW: sdb (256GB SSD)
  #----------------------------------------------------------------------------

    fileSystems."/" = {
        device = "/dev/disk/by-uuid/33b059ad-860f-4ebd-a44b-e0544ac30b82";
        fsType = "btrfs";
        options = [
            "subvol=nixos"
            "compress=zstd" "autodefrag" "noatime"
        ];
    };

    fileSystems."/home" = {
        device = "/dev/disk/by-uuid/33b059ad-860f-4ebd-a44b-e0544ac30b82";
        fsType = "btrfs";
        options = [
            "subvol=home"
            "compress=zstd" "autodefrag" "noatime"
        ];
    };

    # XXX: try disable this because /nix/store mounted twise;
    # but actually is a must need this or it will not start
    # ???
    fileSystems."/nix/store" = {
        device = "/dev/disk/by-uuid/33b059ad-860f-4ebd-a44b-e0544ac30b82";
        fsType = "btrfs";
        options = [
            "subvol=nix-store"
            "compress=zstd" "autodefrag" "noatime"
        ];
    };

    fileSystems."/root" = {
        device = "/dev/disk/by-uuid/33b059ad-860f-4ebd-a44b-e0544ac30b82";
        fsType = "btrfs";
        options = [
            "subvol=root"
            "compress=zstd" "autodefrag" "noatime"
        ];
    };

    fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/4a068210-82a5-4a4c-a160-872cdbecb7f4";
        fsType = "ext4";
        options = [ "noatime" "nodiratime" ];
    };

    swapDevices = [
        #{ device = "/dev/disk/by-uuid/271b7f30-7bf5-48d0-86e5-efe7c12512c1"; } # from 120GB SSD
        { device = "/dev/disk/by-uuid/df87b057-b29b-4687-96e8-c99d49722ab8"; } # from 256GB SSD
    ];
  #----------------------------------------------------------------------------

}
