# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "firewire_ohci" "usb_storage" "sd_mod" ];
  #boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  #----------------------------------------------------------------------
  boot.initrd = {

      # /dev/sda2 --> crypt --> LVM --> btrfs
      # blkid /dev/sda2
      luks.devices."crypt1" = {
          device = "/dev/disk/by-uuid/9273e024-1e66-4bdf-affb-1b26c647f78f"; # "/dev/disk/by-uuid/Ut198v-dhLT-6Joi-V1On-JoU0-29BB-KCweFj";
          preLVM = true;
          #keyFile =
          #allowDiscards =
      };

      # /dev/sdb2 --> crypt --> LVM --> btrfs
      # blkid /dev/sdb2
      luks.devices."crypt2" = {
          device = "/dev/disk/by-uuid/f6bd180c-6557-476b-890e-fd958046f466"; # "/dev/disk/by-uuid/GBeXRg-fwsa-X3bX-Buhe-8FiG-qqm4-07ffhH";
          preLVM = true;
      };

      #secrets =
  };

 # for bringing in filesystem modules.
  boot.initrd.supportedFilesystems = [
      "btrfs"
      "ext4"
      #"zfs"
      "xfs"
      #"bcachefs"
      "vfat"
      "dm-crypt"
      "dm-snapshot"
      "dm-raid"
  ];

  #
  boot.initrd.kernelModules = [
      "btrfs"
      "ext4"
      #"zfs"
      "xfs"
      #"bcachefs"
      "vfat"
      "dm-crypt"
      "dm-snapshot"
      "dm-raid"
  ];

  boot.supportedFilesystems = [
      "ext4"
      "btrfs"
      "xfs"
      #"bcachefs"
      #"zfs"
      "vfat"
  ];


  #----------------------------------------------------------------------
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/fa330ad4-6ae1-403f-a36f-16bef046772f";
      fsType = "btrfs";
      options = [
          "subvol=nixos"
          "compress=zstd"
          "noatime"
          "autodefrag"
      ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/fa330ad4-6ae1-403f-a36f-16bef046772f";
      fsType = "btrfs";
      options = [
          "subvol=home"
          "compress=zstd"
          "noatime"
          "autodefrag"
      ];
    };

  #fileSystems."/home/najib" =
  #  { device = "/dev/disk/by-uuid/70baeff3-72e2-48a8-982f-7653d7af8513";
  #    fsType = "btrfs";
  #    options = [
  #        "subvol=najib"
  #        "compress=zstd"
  #        "noatime"
  #        "autodefrag"
  #    ];
  #  };

  fileSystems."/root" =
    { device = "/dev/disk/by-uuid/fa330ad4-6ae1-403f-a36f-16bef046772f";
      fsType = "btrfs";
      options = [
          "subvol=root"
          "compress=zstd"
          "noatime"
          "autodefrag"
      ];
    };

  fileSystems."/home/DATA" =
    { device = "/dev/disk/by-uuid/fa330ad4-6ae1-403f-a36f-16bef046772f";
      fsType = "btrfs";
      options = [
          "subvol=DATA"
          "compress=zstd"
          "noatime"
          "autodefrag"
      ];
    };

  #-----------------------------------------------------------------
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0ecf5f5f-fd66-4c61-b302-3912c10e02f9"; # sda1
      fsType = "ext4";
    };

  fileSystems."/boot2" =
    { device = "/dev/disk/by-uuid/dc27dde2-df93-405a-9dbd-3c832cc9513b"; # sdb1
      fsType = "ext4";
    };

  # lsblk
  # ls -Filah /dev/mapper/vg1-lvswap1
  # blkid /dev/dm-4
  swapDevices =
    [
      { device = "/dev/disk/by-uuid/9c30e42a-7447-4ffe-85dc-bdedbc046a90"; }
      { device = "/dev/disk/by-uuid/a17f208e-f1d1-4c0b-892f-447cd57a3aef"; }
    ];

}
