# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-9708d2d4-cae7-47fc-9c62-b331b4ab850d";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-9708d2d4-cae7-47fc-9c62-b331b4ab850d".device = "/dev/disk/by-uuid/9708d2d4-cae7-47fc-9c62-b331b4ab850d";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F046-8FF7";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-b21b0aa8-3a6a-4c96-877c-65e63a2f0937"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
